### ISSUE TITLE
module 'lualdap' not found in 0.11

### ISSUE THREAD

**Issue by acislik** [unclev/prosody-docker-extended#13]
Hi,

it seems lualdap can't be found in 0.11 anymore. In 0.10 it works.

```
prosody               | Mar 24 17:42:03 startup info    Hello and welcome to Prosody version 0.11 nightly build 39 (2019-03-22, 68faa0c1a99c)
prosody               | Mar 24 17:42:03 startup info    Prosody is using the select backend for connection handling
prosody               | Mar 24 17:42:03 modulemanager   error   Error initializing module 'auth_ldap' on 'example.org': /usr/lib/prosody/util/startup.lua:144: module 'lualdap' not found:
prosody               |         no field package.preload['lualdap']
prosody               |         no file '/usr/lib/prosody/lualdap.lua'
prosody               |         no file '/usr/local/share/lua/5.2/lualdap.lua'
prosody               |         no file '/usr/local/share/lua/5.2/lualdap/init.lua'
prosody               |         no file '/usr/local/lib/lua/5.2/lualdap.lua'
prosody               |         no file '/usr/local/lib/lua/5.2/lualdap/init.lua'
prosody               |         no file '/usr/share/lua/5.2/lualdap.lua'
prosody               |         no file '/usr/share/lua/5.2/lualdap/init.lua'
prosody               |         no file '/usr/lib/prosody/lualdap.so'
prosody               |         no file '/usr/local/lib/lua/5.2/lualdap.so'
prosody               |         no file '/usr/lib/x86_64-linux-gnu/lua/5.2/lualdap.so'
prosody               |         no file '/usr/lib/lua/5.2/lualdap.so'
prosody               |         no file '/usr/local/lib/lua/5.2/loadall.so'
prosody               | stack traceback:
prosody               |         [C]: in function '_real_require'
prosody               |         /usr/lib/prosody/util/startup.lua:144: in function 'require'
prosody               |         ...rosody/modules-community/mod_auth_ldap/mod_auth_ldap.lua:5: in main chunk
prosody               |         [C]: in function 'xpcall'
prosody               |         /usr/lib/prosody/core/modulemanager.lua:178: in function 'do_load_module'
prosody               |         /usr/lib/prosody/core/modulemanager.lua:256: in function 'load'
prosody               |         /usr/lib/prosody/core/usermanager.lua:67: in function '?'
prosody               |         /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
prosody               |         (...tail calls...)
prosody               |         /usr/lib/prosody/core/hostmanager.lua:108: in function 'activate'
prosody               |         /usr/lib/prosody/core/hostmanager.lua:58: in function '?'
prosody               |         /usr/lib/prosody/util/events.lua:79: in function </usr/lib/prosody/util/events.lua:75>
prosody               |         (...tail calls...)
prosody               |         /usr/lib/prosody/util/startup.lua:330: in function 'prepare_to_start'
prosody               |         /usr/lib/prosody/util/startup.lua:551: in function 'f'
prosody               |         /usr/lib/prosody/util/async.lua:139: in function 'func'
prosody               |         /usr/lib/prosody/util/async.lua:127: in function </usr/lib/prosody/util/async.lua:125>
```

Prosody tries to find _/usr/lib/x86_64-linux-gnu/lua/5.2/lualdap.so_ (lua 5.**2**) but there only seems to be _/usr/lib/x86_64-linux-gnu/lua/5.1/lualdap.so_ (lua 5.**1**) as seen inside the container:
```
/usr/find /usr/ -name "lualdap.so"
/usr/lib/x86_64-linux-gnu/lua/5.1/lualdap.so
```

**Comment by unclev** [comment]
Thank you for pointing on that.

This seems to be a known upgrade issue of [Prosody 0.11](https://prosody.im/doc/release/0.11.0):

> ## Upgrade notes
>
> There are some changes that users running previous versions of Prosody should be aware of:
>
>Note: This release may not work with SQL, LDAP, Cyrus SASL or libevent on some distributions due to missing libraries. Please see the [Lua 5.2 section](https://prosody.im/doc/release/0.11.0#lua-5.2) for more information. Alternatively, use the prosody-0.10 package to stay on Prosody 0.10.x with Lua 5.1.

I've updated the [README](https://github.com/unclev/prosody-docker-extended/tree/0.11).

**Comment by r3pek** [comment]
@unclev what do you think about rebasing the image to ubuntu:disco?

EDIT:
Out of curiosity, I went away and updated the Dockerfile to ":disco". Besides the need to install gnupg before using apt-key, everything went well and is running nicely.

**Comment by unclev** [comment]
Currently Prosody developers do not officially supply Ubuntu 19.04 builds.

I've just created [experimental/0.11-disco](https://github.com/unclev/prosody-docker-extended/tree/experimental/0.11-disco) branch with ubuntu cosmic 0.11 Prosody version in ubuntu:disco, - it builds, but I haven't even tried.

Git Hub: [experimental/0.11-disco](https://github.com/unclev/prosody-docker-extended/tree/experimental/0.11-disco).
Docker Hub: **unclev/prosody-docker-extended:0.11-disco** ([builds](https://hub.docker.com/r/unclev/prosody-docker-extended/builds)).

Everyone is welcome to test!

**Comment by r3pek** [comment]
@unclev i talked with the prosody guys and they have disco now ;)

**Comment by unclev** [comment]
Thank you, @r3pek !

There are couple of new `disco/`: branches:
- [disco/0.11](https://github.com/unclev/prosody-docker-extended/tree/disco/0.11) : image tagged `0.11-disco`,
- [disco/trunk](https://github.com/unclev/prosody-docker-extended/tree/disco/trunk) : image tagged `trunk-disco`.

Docker Hub [tags](https://hub.docker.com/r/unclev/prosody-docker-extended/tags).

@acislik, can you please test if the `unclev/prosody-docker-extended:0.11-disco` image works for you?

**Comment by acislik** [comment]
Looks good. `0.11-disco` works for me.
LDAP module starts and authorization works. 👍 

Thanks
